# Object Oriented Programming (OOP)

In [2]:
from random import randint

class ATM:
    def __init__(self, account_name, bank_name, initial): ## double underscore (dunder)
        self.account_name =account_name
        self.bank_name = bank_name
        self.balance = initial

    ## stromg representation
    def __str__(self):
        return f"This is an account of {self.account_name}, bank: {self.bank_name}"

    ## method => function
    def check_balance(self):
        print(f"Balance: {self.balance}")

    def deposit(self, money):
        self.balance += money
        print(f"Deposit successfully: your new balance: {self.balance} THB")

    def withdraw(self, money):
        self.balance -= money
        print(f"Withdraw successfully: your new balance: {self.balance} THB")

    def get_OTP(self):
        otp = randint(1000, 9999)
        print(f"Your OTP: {otp} This OTP will be available in the next 2 minutes.")

In [3]:
# create an instance from ATM class
acc1 = ATM("Boss", "KBANK", 500)

In [4]:
print(acc1)

This is an account of Boss, bank: KBANK


In [5]:
acc1.check_balance()

Balance: 500


In [6]:
acc1.deposit(1000)

Deposit successfully: your new balance: 1500 THB


In [7]:
acc1.withdraw(1000)

Withdraw successfully: your new balance: 500 THB


In [8]:
acc1.get_OTP()

Your OTP: 7698 This OTP will be available in the next 2 minutes.


# Try Except Block

In [9]:
## Error divide by zero
# 1/0
try:
    1/0
except:
    print("cannot divide by zero")

cannot divide by zero


In [10]:
try:
    1/0
except ZeroDivisionError:
    print("cannot divide by zero")
except NameError:
    print("variable not defined")

cannot divide by zero


In [11]:
try:
    number/0
except ZeroDivisionError:
    print("cannot divide by zero")
except NameError:
    print("variable not defined")

variable not defined


In [12]:
try:
    1/5
except ZeroDivisionError:
    print("cannot divide by zero")
except NameError:
    print("variable not defined")
else:
    print("Done")

Done


In [13]:
try:
    1/5
except ZeroDivisionError:
    print("cannot divide by zero")
except NameError:
    print("variable not defined")
else:
    print("Done")
finally:
    print("Complete!")

Done
Complete!


In [14]:
try:
    1/0
except ZeroDivisionError:
    print("cannot divide by zero")
except NameError:
    print("variable not defined")
else:
    print("Done")
finally:
    print("Complete!")

cannot divide by zero
Complete!


## import csv

In [15]:
## manual version
# import csv (manual version)
import csv

# 3 steps เหมือนกับตอนเปิดโปรแกรมในคอมพิวเตอร์

# 1. Open file
file = open("friends.csv")

# 2. Read file
data = csv.reader(file)
for row in data: # อ่านไฟล์ทีละ row
    print(row)

# 3. Close file
file.close()

['id', 'name', 'age', 'city']
['1', 'toy', '35', 'bangkok']
['2', 'john', '32', 'london']
['3', 'marry', '28', 'seoul']


In [16]:
import csv

# import csv (manual version)
try:
    file = open("friends.csv")
    data = csv.reader(file)
    for row in data: # อ่านไฟล์ทีละ row
        print(row)
    file.close()
except FileNotFoundError:
    print("File not found.")

['id', 'name', 'age', 'city']
['1', 'toy', '35', 'bangkok']
['2', 'john', '32', 'london']
['3', 'marry', '28', 'seoul']


## Context manager version

In [17]:
import csv
# Context manager
result = []

# open and close file automatically
with open("friends.csv", "r") as file: # เปิดไฟล์ แล้วเก็บ(as)ไว้ในชื่อ file
    data = csv.reader(file)
    for row in data:
        result.append(row) # append file to result
try:
    # open and close file automatically
    with open("friends.csv", "r") as file:
        data = csv.reader(file)
        for row in data:
            result.append(row)
except:
    print("file not found")
else:
    print("lod data successfully!")
finally:
    print(result)

lod data successfully!
[['id', 'name', 'age', 'city'], ['1', 'toy', '35', 'bangkok'], ['2', 'john', '32', 'london'], ['3', 'marry', '28', 'seoul'], ['id', 'name', 'age', 'city'], ['1', 'toy', '35', 'bangkok'], ['2', 'john', '32', 'london'], ['3', 'marry', '28', 'seoul']]


## import csv with Pandas

In [18]:
# import csv (easy version)
import pandas as pd
try:
    df = pd.read_csv("friends.csv")
except:
    print("a little error.")
finally:
    print("import file complete!")

import file complete!


In [19]:
df

id 
 name 
 age 
 city 
 
 
 
 
 0 
 1 
 toy 
 35 
 bangkok 
 
 
 1 
 2 
 john 
 32 
 london 
 
 
 2 
 3 
 marry 
 28 
 seoul

## Write csv file

### pandas version

In [20]:
# import csv (easy version)
import pandas as pd
df.to_csv("newCSVFile.csv")

### Manual version

In [21]:
import csv

col_names = ["food_id", "food", "price"]
data = [
    [1, "pizza", 200],
    [2, "french fried", 50],
    [3, "coke", 10]
]

with open("food.csv", "w") as file:
    writer = csv.writer(file)
    writer.writerow(col_names)
    writer.writerows(data)

## JSON

### Read json file by context manager

In [22]:
import json

with open("data.json") as file:
    result = json.load(file)

print(result)

{'id': 1, 'name': 'boss', 'favorite_food': ['coke', 'pizza']}


In [23]:
result["favorite_food"][0]

'coke'

In [24]:
result["favorite_food"].append("hamburger")

In [25]:
result["name"] = "John Wock"

In [26]:
result["city"] = "New York"

In [27]:
result

{'id': 1,
 'name': 'John Wock',
 'favorite_food': ['coke', 'pizza', 'hamburger'],
 'city': 'New York'}

### Write json file by context manager

In [28]:
from json import load, dump

# dump file (in json) = write file

with open("JohnWick.json", "w") as file:
    result = json.dump(result, file, indent=6) # indent คือ ย่อหน้า
    print("successfully dump a new json file.")

successfully dump a new json file.


In [29]:
!cat JohnWick.json

{
      "id": 1,
      "name": "John Wock",
      "favorite_food": [
            "coke",
            "pizza",
            "hamburger"
      ],
      "city": "New York"
}

# Numpy and Pandas

numerical python 

pandas dataframe

In [30]:
import numpy as np
import pandas as pd

In [31]:
## numpy array
nums = [1,20,25,30,100] #vector c(1,20,25,30,100)
arr_nums = np.array(nums)
arr_nums

array([ 1, 20, 25, 30, 100])

In [32]:
print(
    np.sum(arr_nums),
    np.mean(arr_nums),
    np.median(arr_nums),
    np.min(arr_nums),
    np.max(arr_nums),
    np.std(arr_nums),
)
     

176 35.2 25.0 1 100 33.85498486190771


In [33]:
m1 = np.array([
    [1,2],
    [3,4]
])
m1

array([[1, 2],
 [3, 4]])

In [34]:
# Broadcasting
m1 + 100

array([[101, 102],
 [103, 104]])

In [35]:
# element wise computation
m1 + m1

array([[2, 4],
 [6, 8]])

In [36]:

np.ones((3,3))

array([[1., 1., 1.],
 [1., 1., 1.],
 [1., 1., 1.]])

In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
 [0., 0., 0.],
 [0., 0., 0.]])

In [38]:
np.arange(1,101,1)

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
 92, 93, 94, 95, 96, 97, 98, 99, 100])

In [39]:
np.linspace(1, 101, 5)

array([ 1., 26., 51., 76., 101.])

In [42]:
## matrix dot notation
m1 = np.array([
    [1,2],
    [3,4]
])

m2 = np.array([
    [5,5],
    [3,2]
])

In [43]:
np.dot(m1, m2)

array([[11, 9],
 [27, 23]])

In [44]:
np.dot(m2, m1)

array([[20, 30],
 [ 9, 14]])

# Pandas

In [45]:
import pandas as pd
## create dataframe from scratch
data = {
    "id": [1,2,3],
    "name": ["toy", "anna", "jessica"],
    "city": ["BKK", "JPN", "LON"]
}

df = pd.DataFrame(data)

In [46]:
df

id 
 name 
 city 
 
 
 
 
 0 
 1 
 toy 
 BKK 
 
 
 1 
 2 
 anna 
 JPN 
 
 
 2 
 3 
 jessica 
 LON

In [47]:
# add a new column
df["age"] = [35,28,29]
df

id 
 name 
 city 
 age 
 
 
 
 
 0 
 1 
 toy 
 BKK 
 35 
 
 
 1 
 2 
 anna 
 JPN 
 28 
 
 
 2 
 3 
 jessica 
 LON 
 29

In [48]:
df.drop("age", axis="columns")

id 
 name 
 city 
 
 
 
 
 0 
 1 
 toy 
 BKK 
 
 
 1 
 2 
 anna 
 JPN 
 
 
 2 
 3 
 jessica 
 LON

In [50]:
# read csv file from pandas
df = pd.read_csv("store.csv")
df

Row ID 
 Order ID 
 Order Date 
 Ship Date 
 Ship Mode 
 Customer ID 
 Customer Name 
 Segment 
 Country 
 City 
 ... 
 Postal Code 
 Region 
 Product ID 
 Category 
 Sub-Category 
 Product Name 
 Sales 
 Quantity 
 Discount 
 Profit 
 
 
 
 
 0 
 1 
 CA-2016-152156 
 2016-11-08 
 2016-11-11 
 Second Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Henderson 
 ... 
 42420 
 South 
 FUR-BO-10001798 
 Furniture 
 Bookcases 
 Bush Somerset Collection Bookcase 
 261.9600 
 2 
 0.00 
 41.9136 
 
 
 1 
 2 
 CA-2016-152156 
 2016-11-08 
 2016-11-11 
 Second Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Henderson 
 ... 
 42420 
 South 
 FUR-CH-10000454 
 Furniture 
 Chairs 
 Hon Deluxe Fabric Upholstered Stacking Chairs,... 
 731.9400 
 3 
 0.00 
 219.5820 
 
 
 2 
 3 
 CA-2016-138688 
 2016-06-12 
 2016-06-16 
 Second Class 
 DV-13045 
 Darrin Van Huff 
 Corporate 
 United States 
 Los Angeles 
 ... 
 90036 
 West 
 OFF-LA-10000240 
 Office Supplies 
 Labels 
 Self-Adhesive Address Labels for Typewriters b... 
 14.6200 
 2 
 0.00 
 6.8714 
 
 
 3 
 4 
 US-2015-108966 
 2015-10-11 
 2015-10-18 
 Standard Class 
 SO-20335 
 Sean O'Donnell 
 Consumer 
 United States 
 Fort Lauderdale 
 ... 
 33311 
 South 
 FUR-TA-10000577 
 Furniture 
 Tables 
 Bretford CR4500 Series Slim Rectangular Table 
 957.5775 
 5 
 0.45 
 -383.0310 
 
 
 4 
 5 
 US-2015-108966 
 2015-10-11 
 2015-10-18 
 Standard Class 
 SO-20335 
 Sean O'Donnell 
 Consumer 
 United States 
 Fort Lauderdale 
 ... 
 33311 
 South 
 OFF-ST-10000760 
 Office Supplies 
 Storage 
 Eldon Fold 'N Roll Cart System 
 22.3680 
 2 
 0.20 
 2.5164 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 9989 
 9990 
 CA-2014-110422 
 2014-01-21 
 2014-01-23 
 Second Class 
 TB-21400 
 Tom Boeckenhauer 
 Consumer 
 United States 
 Miami 
 ... 
 33180 
 South 
 FUR-FU-10001889 
 Furniture 
 Furnishings 
 Ultra Door Pull Handle 
 25.2480 
 3 
 0.20 
 4.1028 
 
 
 9990 
 9991 
 CA-2017-121258 
 2017-02-26 
 2017-03-03 
 Standard Class 
 DB-13060 
 Dave Brooks 
 Consumer 
 United States 
 Costa Mesa 
 ... 
 92627 
 West 
 FUR-FU-10000747 
 Furniture 
 Furnishings 
 Tenex B1-RE Series Chair Mats for Low Pile Car... 
 91.9600 
 2 
 0.00 
 15.6332 
 
 
 9991 
 9992 
 CA-2017-121258 
 2017-02-26 
 2017-03-03 
 Standard Class 
 DB-13060 
 Dave Brooks 
 Consumer 
 United States 
 Costa Mesa 
 ... 
 92627 
 West 
 TEC-PH-10003645 
 Technology 
 Phones 
 Aastra 57i VoIP phone 
 258.5760 
 2 
 0.20 
 19.3932 
 
 
 9992 
 9993 
 CA-2017-121258 
 2017-02-26 
 2017-03-03 
 Standard Class 
 DB-13060 
 Dave Brooks 
 Consumer 
 United States 
 Costa Mesa 
 ... 
 92627 
 West 
 OFF-PA-10004041 
 Office Supplies 
 Paper 
 It's Hot Message Books with Stickers, 2 3/4" x 5" 
 29.6000 
 4 
 0.00 
 13.3200 
 
 
 9993 
 9994 
 CA-2017-119914 
 2017-05-04 
 2017-05-09 
 Second Class 
 CC-12220 
 Chris Cortes 
 Consumer 
 United States 
 Westminster 
 ... 
 92683 
 West 
 OFF-AP-10002684 
 Office Supplies 
 Appliances 
 Acco 7-Outlet Masterpiece Power Center, Wihtou... 
 243.1600 
 2 
 0.00 
 72.9480 
 
 
 
 9994 rows × 21 columns

In [51]:
df.head()

Row ID 
 Order ID 
 Order Date 
 Ship Date 
 Ship Mode 
 Customer ID 
 Customer Name 
 Segment 
 Country 
 City 
 ... 
 Postal Code 
 Region 
 Product ID 
 Category 
 Sub-Category 
 Product Name 
 Sales 
 Quantity 
 Discount 
 Profit 
 
 
 
 
 0 
 1 
 CA-2016-152156 
 2016-11-08 
 2016-11-11 
 Second Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Henderson 
 ... 
 42420 
 South 
 FUR-BO-10001798 
 Furniture 
 Bookcases 
 Bush Somerset Collection Bookcase 
 261.9600 
 2 
 0.00 
 41.9136 
 
 
 1 
 2 
 CA-2016-152156 
 2016-11-08 
 2016-11-11 
 Second Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Henderson 
 ... 
 42420 
 South 
 FUR-CH-10000454 
 Furniture 
 Chairs 
 Hon Deluxe Fabric Upholstered Stacking Chairs,... 
 731.9400 
 3 
 0.00 
 219.5820 
 
 
 2 
 3 
 CA-2016-138688 
 2016-06-12 
 2016-06-16 
 Second Class 
 DV-13045 
 Darrin Van Huff 
 Corporate 
 United States 
 Los Angeles 
 ... 
 90036 
 West 
 OFF-LA-10000240 
 Office Supplies 
 Labels 
 Self-Adhesive Address Labels for Typewriters b... 
 14.6200 
 2 
 0.00 
 6.8714 
 
 
 3 
 4 
 US-2015-108966 
 2015-10-11 
 2015-10-18 
 Standard Class 
 SO-20335 
 Sean O'Donnell 
 Consumer 
 United States 
 Fort Lauderdale 
 ... 
 33311 
 South 
 FUR-TA-10000577 
 Furniture 
 Tables 
 Bretford CR4500 Series Slim Rectangular Table 
 957.5775 
 5 
 0.45 
 -383.0310 
 
 
 4 
 5 
 US-2015-108966 
 2015-10-11 
 2015-10-18 
 Standard Class 
 SO-20335 
 Sean O'Donnell 
 Consumer 
 United States 
 Fort Lauderdale 
 ... 
 33311 
 South 
 OFF-ST-10000760 
 Office Supplies 
 Storage 
 Eldon Fold 'N Roll Cart System 
 22.3680 
 2 
 0.20 
 2.5164 
 
 
 
 5 rows × 21 columns

In [52]:
df.tail()

Row ID 
 Order ID 
 Order Date 
 Ship Date 
 Ship Mode 
 Customer ID 
 Customer Name 
 Segment 
 Country 
 City 
 ... 
 Postal Code 
 Region 
 Product ID 
 Category 
 Sub-Category 
 Product Name 
 Sales 
 Quantity 
 Discount 
 Profit 
 
 
 
 
 9989 
 9990 
 CA-2014-110422 
 2014-01-21 
 2014-01-23 
 Second Class 
 TB-21400 
 Tom Boeckenhauer 
 Consumer 
 United States 
 Miami 
 ... 
 33180 
 South 
 FUR-FU-10001889 
 Furniture 
 Furnishings 
 Ultra Door Pull Handle 
 25.248 
 3 
 0.2 
 4.1028 
 
 
 9990 
 9991 
 CA-2017-121258 
 2017-02-26 
 2017-03-03 
 Standard Class 
 DB-13060 
 Dave Brooks 
 Consumer 
 United States 
 Costa Mesa 
 ... 
 92627 
 West 
 FUR-FU-10000747 
 Furniture 
 Furnishings 
 Tenex B1-RE Series Chair Mats for Low Pile Car... 
 91.960 
 2 
 0.0 
 15.6332 
 
 
 9991 
 9992 
 CA-2017-121258 
 2017-02-26 
 2017-03-03 
 Standard Class 
 DB-13060 
 Dave Brooks 
 Consumer 
 United States 
 Costa Mesa 
 ... 
 92627 
 West 
 TEC-PH-10003645 
 Technology 
 Phones 
 Aastra 57i VoIP phone 
 258.576 
 2 
 0.2 
 19.3932 
 
 
 9992 
 9993 
 CA-2017-121258 
 2017-02-26 
 2017-03-03 
 Standard Class 
 DB-13060 
 Dave Brooks 
 Consumer 
 United States 
 Costa Mesa 
 ... 
 92627 
 West 
 OFF-PA-10004041 
 Office Supplies 
 Paper 
 It's Hot Message Books with Stickers, 2 3/4" x 5" 
 29.600 
 4 
 0.0 
 13.3200 
 
 
 9993 
 9994 
 CA-2017-119914 
 2017-05-04 
 2017-05-09 
 Second Class 
 CC-12220 
 Chris Cortes 
 Consumer 
 United States 
 Westminster 
 ... 
 92683 
 West 
 OFF-AP-10002684 
 Office Supplies 
 Appliances 
 Acco 7-Outlet Masterpiece Power Center, Wihtou... 
 243.160 
 2 
 0.0 
 72.9480 
 
 
 
 5 rows × 21 columns

In [53]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [54]:
df.shape

(9994, 21)

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9994 non-null   int64  
 1   Order ID       9994 non-null   object 
 2   Order Date     9994 non-null   object 
 3   Ship Date      9994 non-null   object 
 4   Ship Mode      9994 non-null   object 
 5   Customer ID    9994 non-null   object 
 6   Customer Name  9994 non-null   object 
 7   Segment        9994 non-null   object 
 8   Country        9994 non-null   object 
 9   City           9994 non-null   object 
 10  State          9994 non-null   object 
 11  Postal Code    9994 non-null   int64  
 12  Region         9994 non-null   object 
 13  Product ID     9994 non-null   object 
 14  Category       9994 non-null   object 
 15  Sub-Category   9994 non-null   object 
 16  Product Name   9994 non-null   object 
 17  Sales          9994 non-null   float64
 18  Quantity

In [56]:
# clean dataframe column names
col_names = list(df.columns)
clean_col_names = [name.lower().replace(" ", "_").replace("-", "_")
                   for name in col_names]

# assign clean column names to dataframe
df.columns = clean_col_names
df.head()

row_id 
 order_id 
 order_date 
 ship_date 
 ship_mode 
 customer_id 
 customer_name 
 segment 
 country 
 city 
 ... 
 postal_code 
 region 
 product_id 
 category 
 sub_category 
 product_name 
 sales 
 quantity 
 discount 
 profit 
 
 
 
 
 0 
 1 
 CA-2016-152156 
 2016-11-08 
 2016-11-11 
 Second Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Henderson 
 ... 
 42420 
 South 
 FUR-BO-10001798 
 Furniture 
 Bookcases 
 Bush Somerset Collection Bookcase 
 261.9600 
 2 
 0.00 
 41.9136 
 
 
 1 
 2 
 CA-2016-152156 
 2016-11-08 
 2016-11-11 
 Second Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Henderson 
 ... 
 42420 
 South 
 FUR-CH-10000454 
 Furniture 
 Chairs 
 Hon Deluxe Fabric Upholstered Stacking Chairs,... 
 731.9400 
 3 
 0.00 
 219.5820 
 
 
 2 
 3 
 CA-2016-138688 
 2016-06-12 
 2016-06-16 
 Second Class 
 DV-13045 
 Darrin Van Huff 
 Corporate 
 United States 
 Los Angeles 
 ... 
 90036 
 West 
 OFF-LA-10000240 
 Office Supplies 
 Labels 
 Self-Adhesive Address Labels for Typewriters b... 
 14.6200 
 2 
 0.00 
 6.8714 
 
 
 3 
 4 
 US-2015-108966 
 2015-10-11 
 2015-10-18 
 Standard Class 
 SO-20335 
 Sean O'Donnell 
 Consumer 
 United States 
 Fort Lauderdale 
 ... 
 33311 
 South 
 FUR-TA-10000577 
 Furniture 
 Tables 
 Bretford CR4500 Series Slim Rectangular Table 
 957.5775 
 5 
 0.45 
 -383.0310 
 
 
 4 
 5 
 US-2015-108966 
 2015-10-11 
 2015-10-18 
 Standard Class 
 SO-20335 
 Sean O'Donnell 
 Consumer 
 United States 
 Fort Lauderdale 
 ... 
 33311 
 South 
 OFF-ST-10000760 
 Office Supplies 
 Storage 
 Eldon Fold 'N Roll Cart System 
 22.3680 
 2 
 0.20 
 2.5164 
 
 
 
 5 rows × 21 columns

In [57]:
## data transformation
df[["customer_id", "customer_name"]].head(3)

customer_id 
 customer_name 
 
 
 
 
 0 
 CG-12520 
 Claire Gute 
 
 
 1 
 CG-12520 
 Claire Gute 
 
 
 2 
 DV-13045 
 Darrin Van Huff

In [58]:
df[ df["customer_name"] == "Claire Gute" ].head()

row_id 
 order_id 
 order_date 
 ship_date 
 ship_mode 
 customer_id 
 customer_name 
 segment 
 country 
 city 
 ... 
 postal_code 
 region 
 product_id 
 category 
 sub_category 
 product_name 
 sales 
 quantity 
 discount 
 profit 
 
 
 
 
 0 
 1 
 CA-2016-152156 
 2016-11-08 
 2016-11-11 
 Second Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Henderson 
 ... 
 42420 
 South 
 FUR-BO-10001798 
 Furniture 
 Bookcases 
 Bush Somerset Collection Bookcase 
 261.960 
 2 
 0.0 
 41.9136 
 
 
 1 
 2 
 CA-2016-152156 
 2016-11-08 
 2016-11-11 
 Second Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Henderson 
 ... 
 42420 
 South 
 FUR-CH-10000454 
 Furniture 
 Chairs 
 Hon Deluxe Fabric Upholstered Stacking Chairs,... 
 731.940 
 3 
 0.0 
 219.5820 
 
 
 5491 
 5492 
 CA-2017-164098 
 2017-01-26 
 2017-01-27 
 First Class 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Houston 
 ... 
 77070 
 Central 
 OFF-ST-10000615 
 Office Supplies 
 Storage 
 SimpliFile Personal File, Black Granite, 15w x... 
 18.160 
 2 
 0.2 
 1.8160 
 
 
 6877 
 6878 
 US-2015-123918 
 2015-10-15 
 2015-10-15 
 Same Day 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Dallas 
 ... 
 75217 
 Central 
 FUR-FU-10004952 
 Furniture 
 Furnishings 
 C-Line Cubicle Keepers Polyproplyene Holder w/... 
 131.376 
 6 
 0.6 
 -95.2476 
 
 
 6878 
 6879 
 US-2015-123918 
 2015-10-15 
 2015-10-15 
 Same Day 
 CG-12520 
 Claire Gute 
 Consumer 
 United States 
 Dallas 
 ... 
 75217 
 Central 
 OFF-PA-10003001 
 Office Supplies 
 Paper 
 Xerox 1986 
 5.344 
 1 
 0.2 
 1.8704 
 
 
 
 5 rows × 21 columns

In [59]:
df[ df["customer_name"] == "Claire Gute" ][["order_date", "customer_id", "customer_name"]].head()

order_date 
 customer_id 
 customer_name 
 
 
 
 
 0 
 2016-11-08 
 CG-12520 
 Claire Gute 
 
 
 1 
 2016-11-08 
 CG-12520 
 Claire Gute 
 
 
 5491 
 2017-01-26 
 CG-12520 
 Claire Gute 
 
 
 6877 
 2015-10-15 
 CG-12520 
 Claire Gute 
 
 
 6878 
 2015-10-15 
 CG-12520 
 Claire Gute

In [60]:
# query => filter rows with conditions
df.query(" city == 'Los Angeles' ").head()

row_id 
 order_id 
 order_date 
 ship_date 
 ship_mode 
 customer_id 
 customer_name 
 segment 
 country 
 city 
 ... 
 postal_code 
 region 
 product_id 
 category 
 sub_category 
 product_name 
 sales 
 quantity 
 discount 
 profit 
 
 
 
 
 2 
 3 
 CA-2016-138688 
 2016-06-12 
 2016-06-16 
 Second Class 
 DV-13045 
 Darrin Van Huff 
 Corporate 
 United States 
 Los Angeles 
 ... 
 90036 
 West 
 OFF-LA-10000240 
 Office Supplies 
 Labels 
 Self-Adhesive Address Labels for Typewriters b... 
 14.620 
 2 
 0.0 
 6.8714 
 
 
 5 
 6 
 CA-2014-115812 
 2014-06-09 
 2014-06-14 
 Standard Class 
 BH-11710 
 Brosina Hoffman 
 Consumer 
 United States 
 Los Angeles 
 ... 
 90032 
 West 
 FUR-FU-10001487 
 Furniture 
 Furnishings 
 Eldon Expressions Wood and Plastic Desk Access... 
 48.860 
 7 
 0.0 
 14.1694 
 
 
 6 
 7 
 CA-2014-115812 
 2014-06-09 
 2014-06-14 
 Standard Class 
 BH-11710 
 Brosina Hoffman 
 Consumer 
 United States 
 Los Angeles 
 ... 
 90032 
 West 
 OFF-AR-10002833 
 Office Supplies 
 Art 
 Newell 322 
 7.280 
 4 
 0.0 
 1.9656 
 
 
 7 
 8 
 CA-2014-115812 
 2014-06-09 
 2014-06-14 
 Standard Class 
 BH-11710 
 Brosina Hoffman 
 Consumer 
 United States 
 Los Angeles 
 ... 
 90032 
 West 
 TEC-PH-10002275 
 Technology 
 Phones 
 Mitel 5320 IP Phone VoIP phone 
 907.152 
 6 
 0.2 
 90.7152 
 
 
 8 
 9 
 CA-2014-115812 
 2014-06-09 
 2014-06-14 
 Standard Class 
 BH-11710 
 Brosina Hoffman 
 Consumer 
 United States 
 Los Angeles 
 ... 
 90032 
 West 
 OFF-BI-10003910 
 Office Supplies 
 Binders 
 DXL Angle-View Binders with Locking Rings by S... 
 18.504 
 3 
 0.2 
 5.7825 
 
 
 
 5 rows × 21 columns

In [61]:
# query => filter rows with conditions
df.query(" city == 'Los Angeles' and category == 'Furniture' ").head()

row_id 
 order_id 
 order_date 
 ship_date 
 ship_mode 
 customer_id 
 customer_name 
 segment 
 country 
 city 
 ... 
 postal_code 
 region 
 product_id 
 category 
 sub_category 
 product_name 
 sales 
 quantity 
 discount 
 profit 
 
 
 
 
 5 
 6 
 CA-2014-115812 
 2014-06-09 
 2014-06-14 
 Standard Class 
 BH-11710 
 Brosina Hoffman 
 Consumer 
 United States 
 Los Angeles 
 ... 
 90032 
 West 
 FUR-FU-10001487 
 Furniture 
 Furnishings 
 Eldon Expressions Wood and Plastic Desk Access... 
 48.860 
 7 
 0.0 
 14.1694 
 
 
 10 
 11 
 CA-2014-115812 
 2014-06-09 
 2014-06-14 
 Standard Class 
 BH-11710 
 Brosina Hoffman 
 Consumer 
 United States 
 Los Angeles 
 ... 
 90032 
 West 
 FUR-TA-10001539 
 Furniture 
 Tables 
 Chromcraft Rectangular Conference Tables 
 1706.184 
 9 
 0.2 
 85.3092 
 
 
 65 
 66 
 CA-2015-135545 
 2015-11-24 
 2015-11-30 
 Standard Class 
 KM-16720 
 Kunst Miller 
 Consumer 
 United States 
 Los Angeles 
 ... 
 90004 
 West 
 FUR-FU-10000397 
 Furniture 
 Furnishings 
 Luxo Economy Swing Arm Lamp 
 79.760 
 4 
 0.0 
 22.3328 
 
 
 128 
 129 
 US-2016-125969 
 2016-11-06 
 2016-11-10 
 Second Class 
 LS-16975 
 Lindsay Shagiari 
 Home Office 
 United States 
 Los Angeles 
 ... 
 90004 
 West 
 FUR-CH-10001146 
 Furniture 
 Chairs 
 Global Task Chair, Black 
 81.424 
 2 
 0.2 
 -9.1602 
 
 
 129 
 130 
 US-2016-125969 
 2016-11-06 
 2016-11-10 
 Second Class 
 LS-16975 
 Lindsay Shagiari 
 Home Office 
 United States 
 Los Angeles 
 ... 
 90004 
 West 
 FUR-FU-10003773 
 Furniture 
 Furnishings 
 Eldon Cleatmat Plus Chair Mats for High Pile C... 
 238.560 
 3 
 0.0 
 26.2416 
 
 
 
 5 rows × 21 columns

In [62]:
# query => filter rows with conditions
df.query(" city == 'Los Angeles' and category == 'Furniture' ")[["customer_name", "segment", "city"]].head()

customer_name 
 segment 
 city 
 
 
 
 
 5 
 Brosina Hoffman 
 Consumer 
 Los Angeles 
 
 
 10 
 Brosina Hoffman 
 Consumer 
 Los Angeles 
 
 
 65 
 Kunst Miller 
 Consumer 
 Los Angeles 
 
 
 128 
 Lindsay Shagiari 
 Home Office 
 Los Angeles 
 
 
 129 
 Lindsay Shagiari 
 Home Office 
 Los Angeles

In [63]:
## aggregate data
df.groupby("segment")["sales"].sum()

segment
Consumer 1.161401e+06
Corporate 7.061464e+05
Home Office 4.296531e+05
Name: sales, dtype: float64

In [64]:
## aggregate data
df.groupby(["segment", "region"])["sales"].sum()

segment region 
Consumer Central 252031.4340
 East 350908.1670
 South 195580.9710
 West 362880.7730
Corporate Central 157995.8128
 East 200409.3470
 South 121885.9325
 West 225855.2745
Home Office Central 91212.6440
 East 127463.7260
 South 74255.0015
 West 136721.7770
Name: sales, dtype: float64

In [65]:
## aggregate data
df.groupby(["segment", "region"])[["sales", "profit"]].sum()

sales 
 profit 
 
 
 segment 
 region 
 
 
 
 
 
 
 Consumer 
 Central 
 252031.4340 
 8564.0481 
 
 
 East 
 350908.1670 
 41190.9843 
 
 
 South 
 195580.9710 
 26913.5728 
 
 
 West 
 362880.7730 
 57450.6040 
 
 
 Corporate 
 Central 
 157995.8128 
 18703.9020 
 
 
 East 
 200409.3470 
 23622.5789 
 
 
 South 
 121885.9325 
 15215.2232 
 
 
 West 
 225855.2745 
 34437.4299 
 
 
 Home Office 
 Central 
 91212.6440 
 12438.4124 
 
 
 East 
 127463.7260 
 26709.2168 
 
 
 South 
 74255.0015 
 4620.6343 
 
 
 West 
 136721.7770 
 16530.4150

In [66]:
## aggregate data
df.groupby(["segment", "region"])[["sales", "profit"]].agg(['sum', 'mean'])

sales 
 profit 
 
 
 
 
 sum 
 mean 
 sum 
 mean 
 
 
 segment 
 region 
 
 
 
 
 
 
 
 
 Consumer 
 Central 
 252031.4340 
 207.946728 
 8564.0481 
 7.066046 
 
 
 East 
 350908.1670 
 238.875539 
 41190.9843 
 28.040153 
 
 
 South 
 195580.9710 
 233.390180 
 26913.5728 
 32.116435 
 
 
 West 
 362880.7730 
 217.033955 
 57450.6040 
 34.360409 
 
 
 Corporate 
 Central 
 157995.8128 
 234.763466 
 18703.9020 
 27.791831 
 
 
 East 
 200409.3470 
 228.516929 
 23622.5789 
 26.935666 
 
 
 South 
 121885.9325 
 238.992025 
 15215.2232 
 29.833771 
 
 
 West 
 225855.2745 
 235.265911 
 34437.4299 
 35.872323 
 
 
 Home Office 
 Central 
 91212.6440 
 208.248046 
 12438.4124 
 28.398202 
 
 
 East 
 127463.7260 
 253.911805 
 26709.2168 
 53.205611 
 
 
 South 
 74255.0015 
 272.996329 
 4620.6343 
 16.987626 
 
 
 West 
 136721.7770 
 239.442692 
 16530.4150 
 28.949939

In [67]:
## aggregate data
df.groupby(["segment", "region"])[["sales", "profit"]].agg(['sum', 'mean']).reset_index()

segment 
 region 
 sales 
 profit 
 
 
 
 
 
 sum 
 mean 
 sum 
 mean 
 
 
 
 
 0 
 Consumer 
 Central 
 252031.4340 
 207.946728 
 8564.0481 
 7.066046 
 
 
 1 
 Consumer 
 East 
 350908.1670 
 238.875539 
 41190.9843 
 28.040153 
 
 
 2 
 Consumer 
 South 
 195580.9710 
 233.390180 
 26913.5728 
 32.116435 
 
 
 3 
 Consumer 
 West 
 362880.7730 
 217.033955 
 57450.6040 
 34.360409 
 
 
 4 
 Corporate 
 Central 
 157995.8128 
 234.763466 
 18703.9020 
 27.791831 
 
 
 5 
 Corporate 
 East 
 200409.3470 
 228.516929 
 23622.5789 
 26.935666 
 
 
 6 
 Corporate 
 South 
 121885.9325 
 238.992025 
 15215.2232 
 29.833771 
 
 
 7 
 Corporate 
 West 
 225855.2745 
 235.265911 
 34437.4299 
 35.872323 
 
 
 8 
 Home Office 
 Central 
 91212.6440 
 208.248046 
 12438.4124 
 28.398202 
 
 
 9 
 Home Office 
 East 
 127463.7260 
 253.911805 
 26709.2168 
 53.205611 
 
 
 10 
 Home Office 
 South 
 74255.0015 
 272.996329 
 4620.6343 
 16.987626 
 
 
 11 
 Home Office 
 West 
 136721.7770 
 239.442692 
 16530.4150 
 28.949939

In [68]:
## aggregate data
df.groupby(["segment", "region"])[["sales", "profit"]].agg(['sum', 'mean', 'count']).reset_index()

segment 
 region 
 sales 
 profit 
 
 
 
 
 
 sum 
 mean 
 count 
 sum 
 mean 
 count 
 
 
 
 
 0 
 Consumer 
 Central 
 252031.4340 
 207.946728 
 1212 
 8564.0481 
 7.066046 
 1212 
 
 
 1 
 Consumer 
 East 
 350908.1670 
 238.875539 
 1469 
 41190.9843 
 28.040153 
 1469 
 
 
 2 
 Consumer 
 South 
 195580.9710 
 233.390180 
 838 
 26913.5728 
 32.116435 
 838 
 
 
 3 
 Consumer 
 West 
 362880.7730 
 217.033955 
 1672 
 57450.6040 
 34.360409 
 1672 
 
 
 4 
 Corporate 
 Central 
 157995.8128 
 234.763466 
 673 
 18703.9020 
 27.791831 
 673 
 
 
 5 
 Corporate 
 East 
 200409.3470 
 228.516929 
 877 
 23622.5789 
 26.935666 
 877 
 
 
 6 
 Corporate 
 South 
 121885.9325 
 238.992025 
 510 
 15215.2232 
 29.833771 
 510 
 
 
 7 
 Corporate 
 West 
 225855.2745 
 235.265911 
 960 
 34437.4299 
 35.872323 
 960 
 
 
 8 
 Home Office 
 Central 
 91212.6440 
 208.248046 
 438 
 12438.4124 
 28.398202 
 438 
 
 
 9 
 Home Office 
 East 
 127463.7260 
 253.911805 
 502 
 26709.2168 
 53.205611 
 502 
 
 
 10 
 Home Office 
 South 
 74255.0015 
 272.996329 
 272 
 4620.6343 
 16.987626 
 272 
 
 
 11 
 Home Office 
 West 
 136721.7770 
 239.442692 
 571 
 16530.4150 
 28.949939 
 571

In [69]:
## aggregate data
res = df.groupby(["segment", "region"])[["sales", "profit"]] \
        .agg(['sum', 'mean', 'count']) \
        .reset_index()
print(res)

res.to_csv("agg_data.csv")

        segment   region        sales                        profit  \
                                  sum        mean count         sum   
0      Consumer  Central  252031.4340  207.946728  1212   8564.0481   
1      Consumer     East  350908.1670  238.875539  1469  41190.9843   
2      Consumer    South  195580.9710  233.390180   838  26913.5728   
3      Consumer     West  362880.7730  217.033955  1672  57450.6040   
4     Corporate  Central  157995.8128  234.763466   673  18703.9020   
5     Corporate     East  200409.3470  228.516929   877  23622.5789   
6     Corporate    South  121885.9325  238.992025   510  15215.2232   
7     Corporate     West  225855.2745  235.265911   960  34437.4299   
8   Home Office  Central   91212.6440  208.248046   438  12438.4124   
9   Home Office     East  127463.7260  253.911805   502  26709.2168   
10  Home Office    South   74255.0015  272.996329   272   4620.6343   
11  Home Office     West  136721.7770  239.442692   571  16530.4150   

     

In [70]:
## aggregate data
res = df.query(" region == 'West' ") \
		.groupby(["segment", "region"])[["sales", "profit"]] \
        .agg(['sum', 'mean', 'count']) \
        .reset_index()
res

segment 
 region 
 sales 
 profit 
 
 
 
 
 
 sum 
 mean 
 count 
 sum 
 mean 
 count 
 
 
 
 
 0 
 Consumer 
 West 
 362880.7730 
 217.033955 
 1672 
 57450.6040 
 34.360409 
 1672 
 
 
 1 
 Corporate 
 West 
 225855.2745 
 235.265911 
 960 
 34437.4299 
 35.872323 
 960 
 
 
 2 
 Home Office 
 West 
 136721.7770 
 239.442692 
 571 
 16530.4150 
 28.949939 
 571

# Load data from SQLite

In [71]:
import sqlite3
import pandas as pd

## create connection
con = sqlite3.connect("chinook.db")

In [72]:
con

In [73]:
custs = pd.read_sql("select * from customers where country='USA'", con)
custs

CustomerId 
 FirstName 
 LastName 
 Company 
 Address 
 City 
 State 
 Country 
 PostalCode 
 Phone 
 Fax 
 Email 
 SupportRepId 
 
 
 
 
 0 
 16 
 Frank 
 Harris 
 Google Inc. 
 1600 Amphitheatre Parkway 
 Mountain View 
 CA 
 USA 
 94043-1351 
 +1 (650) 253-0000 
 +1 (650) 253-0000 
 fharris@google.com 
 4 
 
 
 1 
 17 
 Jack 
 Smith 
 Microsoft Corporation 
 1 Microsoft Way 
 Redmond 
 WA 
 USA 
 98052-8300 
 +1 (425) 882-8080 
 +1 (425) 882-8081 
 jacksmith@microsoft.com 
 5 
 
 
 2 
 18 
 Michelle 
 Brooks 
 None 
 627 Broadway 
 New York 
 NY 
 USA 
 10012-2612 
 +1 (212) 221-3546 
 +1 (212) 221-4679 
 michelleb@aol.com 
 3 
 
 
 3 
 19 
 Tim 
 Goyer 
 Apple Inc. 
 1 Infinite Loop 
 Cupertino 
 CA 
 USA 
 95014 
 +1 (408) 996-1010 
 +1 (408) 996-1011 
 tgoyer@apple.com 
 3 
 
 
 4 
 20 
 Dan 
 Miller 
 None 
 541 Del Medio Avenue 
 Mountain View 
 CA 
 USA 
 94040-111 
 +1 (650) 644-3358 
 None 
 dmiller@comcast.com 
 4 
 
 
 5 
 21 
 Kathy 
 Chase 
 None 
 801 W 4th Street 
 Reno 
 NV 
 USA 
 89503 
 +1 (775) 223-7665 
 None 
 kachase@hotmail.com 
 5 
 
 
 6 
 22 
 Heather 
 Leacock 
 None 
 120 S Orange Ave 
 Orlando 
 FL 
 USA 
 32801 
 +1 (407) 999-7788 
 None 
 hleacock@gmail.com 
 4 
 
 
 7 
 23 
 John 
 Gordon 
 None 
 69 Salem Street 
 Boston 
 MA 
 USA 
 2113 
 +1 (617) 522-1333 
 None 
 johngordon22@yahoo.com 
 4 
 
 
 8 
 24 
 Frank 
 Ralston 
 None 
 162 E Superior Street 
 Chicago 
 IL 
 USA 
 60611 
 +1 (312) 332-3232 
 None 
 fralston@gmail.com 
 3 
 
 
 9 
 25 
 Victor 
 Stevens 
 None 
 319 N. Frances Street 
 Madison 
 WI 
 USA 
 53703 
 +1 (608) 257-0597 
 None 
 vstevens@yahoo.com 
 5 
 
 
 10 
 26 
 Richard 
 Cunningham 
 None 
 2211 W Berry Street 
 Fort Worth 
 TX 
 USA 
 76110 
 +1 (817) 924-7272 
 None 
 ricunningham@hotmail.com 
 4 
 
 
 11 
 27 
 Patrick 
 Gray 
 None 
 1033 N Park Ave 
 Tucson 
 AZ 
 USA 
 85719 
 +1 (520) 622-4200 
 None 
 patrick.gray@aol.com 
 4 
 
 
 12 
 28 
 Julia 
 Barnett 
 None 
 302 S 700 E 
 Salt Lake City 
 UT 
 USA 
 84102 
 +1 (801) 531-7272 
 None 
 jubarnett@gmail.com 
 5

In [74]:
con.close()

# Sklearn Foundation

In [75]:
import pandas as pd

url = "https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv"
mtcars = pd.read_csv(url)

In [76]:
mtcars.head(3)

model 
 mpg 
 cyl 
 disp 
 hp 
 drat 
 wt 
 qsec 
 vs 
 am 
 gear 
 carb 
 
 
 
 
 0 
 Mazda RX4 
 21.0 
 6 
 160.0 
 110 
 3.90 
 2.620 
 16.46 
 0 
 1 
 4 
 4 
 
 
 1 
 Mazda RX4 Wag 
 21.0 
 6 
 160.0 
 110 
 3.90 
 2.875 
 17.02 
 0 
 1 
 4 
 4 
 
 
 2 
 Datsun 710 
 22.8 
 4 
 108.0 
 93 
 3.85 
 2.320 
 18.61 
 1 
 1 
 4 
 1

## Regression problem

In [78]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

## 1. split data
y = mtcars["mpg"]
X = mtcars[["hp", "wt", "am"]]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=19
)

## 2. train model
model = LinearRegression()
model.fit(X_train, y_train) ## model fitting

## 3. score (predict data)
train_error = model.score(X_train, y_train)

## 4. evaluate
test_error = model.score(X_test, y_test)

print(train_error, test_error)

0.8237392186558011 0.8955384159803106


In [79]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

## 1. split data
y = mtcars["mpg"]
X = mtcars[["hp", "wt", "am"]]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=19
)

## 2. train model
model = LinearRegression()
model.fit(X_train, y_train) ## model fitting

## 3. score (predict data)
train_error = model.score(X_train, y_train)

## 4. evaluate
test_error = model.score(X_test, y_test)

print(train_error, test_error)

0.8237392186558011 0.8955384159803106


In [80]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

## 1. split data
y = mtcars["mpg"]
X = mtcars[["hp", "wt", "am"]]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=19
)

## 2. train model
model = DecisionTreeRegressor()
model.fit(X_train, y_train) ## model fitting

## 3. score (predict data)
train_error = model.score(X_train, y_train)

## 4. evaluate
test_error = model.score(X_test, y_test)

print(train_error, test_error)

0.9989225398506333 0.47372447952321517


In [81]:
def rmse(actual, pred):
    error = actual - pred
    return np.sqrt(np.mean((error ** 2)))

In [82]:
actual = np.array([1,2,3])
pred = np.array([1,2,1])

rmse(actual, pred)

1.1547005383792515

## Classification problem

In [83]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

## 1. split data
y = mtcars["am"]
X = mtcars[["hp", "wt", "cyl"]]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=19
)

## 2. train model
model = LogisticRegression()
model.fit(X_train, y_train) ## model fitting

## 3. score (predict data)
train_error = model.score(X_train, y_train)

## 4. evaluate
test_error = model.score(X_test, y_test)

print(train_error, test_error)

0.88 1.0
