# Programing Foundation

- variable
- data type
- data structure
- function
- control flow

## **Variable**

In [ ]:
income <- 35000
expense <- 25000
saving <- income - expense

print(saving)

[1] 10000


In [ ]:
print(income)
print(expense)
print(saving)

[1] 35000
[1] 25000
[1] 10000


In [ ]:
my_name <- "Boss"

In [ ]:
my_name

[1] "Boss"

In [ ]:
# remove
rm(my_name)

In [ ]:
# saving income for 10 year, interest rate 5%

income * (1+0.05)**10

[1] 57011.31

## **Data type**

- numeric
- charecter(text,string)
- logical(TRUE,FALSE)
- date

In [ ]:
# numeric
gpa <- 3.41
print(gpa)

[1] 3.41


In [ ]:
age <- 23
print(age)
print(class(age))

[1] 23
[1] "numeric"


In [ ]:
# charecter
class("hello world")

[1] "character"

In [ ]:
## concat two charecter
paste0("hello","world")

[1] "helloworld"

In [ ]:
paste("hello","world","hahahah")

[1] "hello world hahahah"

In [ ]:
# logical (TRUE,FALSE)
class(TRUE)
class(T)

[1] "logical"

[1] "logical"

In [ ]:
1+1==2

[1] TRUE

In [ ]:
5>3

[1] TRUE

In [ ]:
# date
today_date <- as.Date("2023-11-11")
print(today_date)
print(class(today_date))

[1] "2023-11-11"
[1] "Date"


In [ ]:
## as.____() chang data type
as.integer(FALSE)

[1] 0

## **Data stucture**
- vector (sigle data type)
- matirx (sigle data type)
- list
- dataframe

In [ ]:
# vector
score <- c(88, 90, 50, 65, 76)

In [ ]:
## vectorization (no need to write loop)
score > 80

[1]  TRUE  TRUE FALSE FALSE FALSE

In [ ]:
## subset
score <- c(john = 88,
          minnie = 90,
          david = 50,
          marry = 65,
          anna = 76)
score

john minnie  david  marry   anna 
    88     90     50     65     76

In [ ]:
### index start at 1
### by name
### by position
### by condition
score["marry"]
score[1]
score[score > 80]

marry 
   65

john 
  88

john minnie 
    88     90

In [ ]:
## update value
score["anna"] <- 70

In [ ]:
## friends 5 persons
friends <- c("boss","toy","john","marry","non")

In [ ]:
paste("hi",friends)

[1] "hi boss"  "hi toy"   "hi john"  "hi marry" "hi non"

In [ ]:
# matrix => 2 dimensions
m <- matrix(1:10, ncol = 5)
m1 <- matrix(1:10, ncol = 5, byrow = T)
m
m1

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [ ]:
## matrix mutiplication
m1 <- matrix(c(2,4,5,10), ncol = 2)
m2 <- matrix(c(1,1,5,2), ncol = 2)

m1;m2

[,1] [,2]
[1,] 2     5  
[2,] 4    10

[,1] [,2]
[1,] 1    5   
[2,] 1    2

In [ ]:
m1*m2

[,1] [,2]
[1,] 2    25  
[2,] 4    20

In [ ]:
## dot operation
m1 %*% m2

[,1] [,2]
[1,]  7   20  
[2,] 14   40

In [ ]:
## dim (dimension)
dim(m1)

[1] 2 2

In [ ]:
# list , dataframe
customer01 <- list(
  name = "boss",
  age = 23,
  city = "bangkok",
  favorite_films = c("Dark knight","Iron man")
)

customer02 <- list(
  name = "lisa",
  age = 21,
  city = "bangkok",
  favorite_films = c("About time","The conjuring")
)
## nested list
list_customers <- list(customer01,customer02)

In [ ]:
my_list["age"] ## return list

$age
[1] 23

In [ ]:
my_list[["age"]] ## return value

[1] 23

In [ ]:
my_list["favorite_films"]

$favorite_films
[1] "Dark knight" "Iron man"

In [ ]:
my_list[["favorite_films"]][1]

[1] "Dark knight"

In [ ]:
list_customers[[1]]["age"]

$age
[1] 23

In [ ]:
# dataframe (the most important in data analyst role)

## create  a new dataframe from scratch
df <- data.frame(
    id = 1:5,
    name = c("toy","john","marry","jane","anne"),
    age = c(28,30,31,22,25),
    movie_lover = c(T,T,F,F,T)
)


In [ ]:
df

id name  age movie_lover
1 1  toy   28   TRUE      
2 2  john  30   TRUE      
3 3  marry 31  FALSE      
4 4  jane  22  FALSE      
5 5  anne  25   TRUE

In [ ]:
## subset dataframe
df[1:3,1]

[1] 1 2 3

In [ ]:
df[1:3, ]

id name  age movie_lover
1 1  toy   28   TRUE      
2 2  john  30   TRUE      
3 3  marry 31  FALSE

In [ ]:
df[c(1,3,5), ]

id name  age movie_lover
1 1  toy   28   TRUE      
3 3  marry 31  FALSE      
5 5  anne  25   TRUE

In [ ]:
df[!df$movie_lover, ]

id name  age movie_lover
3 3  marry 31  FALSE      
4 4  jane  22  FALSE

In [ ]:
### by condition
#### AND
df[df$age >= 30 & df$movie_lover, ]

id name age movie_lover
2 2  john 30  TRUE

In [ ]:
#### OR
df[df$age >= 30 | df$movie_lover, ]


id name  age movie_lover
1 1  toy   28   TRUE      
2 2  john  30   TRUE      
3 3  marry 31  FALSE      
5 5  anne  25   TRUE

In [ ]:
## create city (new column)
df$city <- c(rep("BKK",3),rep("London",2))
df

id name  age movie_lover city  
1 1  toy   28   TRUE       BKK   
2 2  john  30   TRUE       BKK   
3 3  marry 31  FALSE       BKK   
4 4  jane  22  FALSE       London
5 5  anne  25   TRUE       London

In [ ]:
df$random <- 100
df

id name  age movie_lover city   random
1 1  toy   28   TRUE       BKK    100   
2 2  john  30   TRUE       BKK    100   
3 3  marry 31  FALSE       BKK    100   
4 4  jane  22  FALSE       London 100   
5 5  anne  25   TRUE       London 100

In [ ]:
## remove column
df$random <- NULL
df

id name  age movie_lover city  
1 1  toy   28   TRUE       BKK   
2 2  john  30   TRUE       BKK   
3 3  marry 31  FALSE       BKK   
4 4  jane  22  FALSE       London
5 5  anne  25   TRUE       London

In [ ]:
## write csv file
###(if you don't want a new column name set row.name is false)
write.csv(df,"movie.csv",row.names = FALSE)

In [ ]:
## read csv file
movie <- read.csv("movie.csv")
movie

id name  age movie_lover city  
1 1  toy   28   TRUE       BKK   
2 2  john  30   TRUE       BKK   
3 3  marry 31  FALSE       BKK   
4 4  jane  22  FALSE       London
5 5  anne  25   TRUE       London

In [ ]:
## preview top row of data
head(movie,2)

id name age movie_lover city
1 1  toy  28  TRUE        BKK 
2 2  john 30  TRUE        BKK

In [ ]:
## preview bottom row of data
tail(movie,2)

id name age movie_lover city  
4 4  jane 22  FALSE       London
5 5  anne 25   TRUE       London

In [ ]:
## preview data
str(movie)

'data.frame':	5 obs. of  5 variables:
 $ id         : int  1 2 3 4 5
 $ name       : chr  "toy" "john" "marry" "jane" ...
 $ age        : int  28 30 31 22 25
 $ movie_lover: logi  TRUE TRUE FALSE FALSE TRUE
 $ city       : chr  "BKK" "BKK" "BKK" "London" ...


##**Function**

In [ ]:
sum(1:100)

[1] 5050

In [ ]:
my_secret_formula <- function(start,end){
      (start + end)*end/2
}
my_secret_formula(1,100)

[1] 5050

In [ ]:
greeting <- function(name){
  print(paste("hi",name))
}
greeting("boss")

[1] "hi boss"


### **function take user input**

In [ ]:
## get input charecter
user <- readline("What is your name: ")
password <- as.integer(readline("Password: "))

what is your name: boss
Password: 123123


In [ ]:
class(user)
class(password)

[1] "character"

[1] "integer"

In [ ]:
greetingv2 <- function(){
    user_name <- readline("What is your name: ")
    text = paste("Good moring!",user_name)
    return(text)
}

In [ ]:
greetingv2()

What is your name: boss


[1] "Goodmoring boss"

## **Control Flow**
- if
- for loop
- while loop

In [ ]:
# if
# ifelse
# = IF() in google sheet

score <- 79
ifelse(score >= 80,"passed","failed")

[1] "failed"

In [ ]:
## if-else
grading <- function(score){
  if(score >= 80){
    return("A")
  }   else if(score >=70){
    return("B")
  }   else if(score >= 60){
    return("C")
  }   else if (score >= 50){
    return("D")
  }   else{
    return("Failed")
  }
}

In [ ]:
## function is re-usable
grading(88)

[1] "A"

In [ ]:
# for loop
#(ไม่จำเป็นต้องใช้ใน R)
# (cause vectorization)

fruits <- c("banana", "apple", "pineapple")

In [ ]:
for (fruit in fruits) {
  print(toupper(fruit))
}

[1] "BANANA"
[1] "APPLE"
[1] "PINEAPPLE"


In [ ]:
toupper(fruits)

[1] "BANANA"    "APPLE"     "PINEAPPLE"

In [ ]:
# while loop
count <- 0
while(count < 5) {
  print("Hi!")
  count <- count + 1
}

[1] "Hi!"
[1] "Hi!"
[1] "Hi!"
[1] "Hi!"
[1] "Hi!"
